spring:
  profiles:
    active: local
  application:
    name: faq-bot
  ai:
    vectorstore:
      milvus:
        client:
          host: ${spring.ai.vectorstore.milvus.client.host}
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        embeddingDimension: 1024
        collection-name: vector_store
        initialize-schema: true  # 自动创建集合
        enable-index: true       # 自动创建索引
        index-type: IVF_FLAT    # 指定索引类型
        metric-type: COSINE     # 指定距离度量类型
        index-params: '{"nlist": 1024}'  # 索引参数
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${spring.ai.openai.api-key}
      embedding:
        options:
          model: text-embedding-v4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.ai.vectorstore.milvus.client.host}/faq_bot?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml


